## GETING ALL  TOURS
GET http://127.0.0.1:5000/api/v1/tours/monthly-plan?year=2021
## GETING ALL  TOURS

### get all tours
GET http://127.0.0.1:5000/api/v1/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDE5MTk3OCwiZXhwIjoxNzUxOTY3OTc4fQ.zpZxTF3syBcwbRJ7hF8NCJBDPEReasp6LI6Sv0j8eqk
### delete a  tour
DELETE   http://127.0.0.1:5000/api/v1/tours/67e05f3c72e1e84b0725b527
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDE5MjE5MiwiZXhwIjoxNzUxOTY4MTkyfQ.yGvs7t7W97zxoz6s7kPot7rwEc8mE1tG7k9ZS41OvYE

### get a single tour
GET http://127.0.0.1:5000/api/v1/tours/67e05fkkkkc72e1e84b0725b528


### post a tour
POST  http://127.0.0.1:5000/api/v1/tours
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDE5MTk3OCwiZXhwIjoxNzUxOTY3OTc4fQ.zpZxTF3syBcwbRJ7hF8NCJBDPEReasp6LI6Sv0j8eqk
Content-Type: application/json

{
     "name": "The secret Gazer",
    "duration": 9,2
    "maxGroupSize": 8,
    "difficulty": "medium",
    "ratingsAverage": 4.7,
    "ratingsQuantity": 28,
    "price": 2997,
    "summary": "The most remote and stunningly beautiful places for seeing the night sky",
    "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "imageCover": "tour-8-cover.jpg",
    "images": ["tour-8-1.jpg", "tour-8-2.jpg", "tour-8-3.jpg"],
    "startDates": ["2021-03-23,10:00", "2021-10-25,10:00", "2022-01-30,10:00"],
    "secretTour":true
  }


### signup a new user 
POST  http://127.0.0.1:5000/api/v1/users/signup
Content-Type: application/json

{
  "name":"user",
  "email":"user@gmail.com",
  "password":"useruser",
  "conformpassword":"useruser"
}

### login the user
POST  http://127.0.0.1:5000/api/v1/users/login
Content-Type: application/json

{
  "email":"user@gmail.com",
  "password":"useruser"
}


### login the user
GET   http://127.0.0.1:5000/api/v1/users
Content-Type: application/json

{
  "email":"test8@gmail.com",
  "password":"passsword"
}

### forgote a password for the user 
post   http://127.0.0.1:5000/api/v1/users/forgotepassword
Content-Type: application/json

{
  "email":"user@gmail.com"
}

### reset the pasword with the sended token  
post   http://127.0.0.1:5000/api/v1/users/resetpassword/0e56282663900707305fb77dea006e8ee5bcd17c88df6d0eb91ef1f7b451fb04
Content-Type: application/json

{
  "password":"useruser",
  "conformpassword":"useruser"
}

### update the user pasword

post http://127.0.0.1:5000/api/v1/users/updatepassword/67f641e9db2dc10c7040be85
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDIwMTkyMCwiZXhwIjoxNzUxOTc3OTIwfQ.3yjHwjksz2oUAiSCMwJdZ5Wizrft3PCCPXeRSPMQOME
Content-Type: application/json

{
  "passwordCurrent":"useruser",
  "password":"useruser",
  "conformpassword":"useruser"

}

### delete a user 
post   http://127.0.0.1:5000/api/v1/users/deleteme
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDIwMTkyMCwiZXhwIjoxNzUxOTc3OTIwfQ.3yjHwjksz2oUAiSCMwJdZ5Wizrft3PCCPXeRSPMQOME
Content-Type: application/json

### get all users
GET http://127.0.0.1:5000/api/v1/users

### delete a  tour