## GETING ALL  TOURS
GET http://127.0.0.1:5000/api/v1/tours/monthly-plan?year=2021
## GETING ALL  TOURS

### get all tours
GET http://127.0.0.1:5000/api/v1/tours
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTc0NDUwODgzMSwiZXhwIjoxNzUyMjg0ODMxfQ.bcqDxq8vAipzOcqumsrnQGw1QpnsxPad3lAlgXNJT_s
Content-Type: application/json
### delete a  tour
DELETE   http://127.0.0.1:5000/api/v1/tours/5c88fa8cf4afda39709c2955
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE3N2I5NzYzMWRmOTRjMmE4ZmE4ZCIsImlhdCI6MTc0NDQ2Nzg5OCwiZXhwIjoxNzUyMjQzODk4fQ.PTEkFPwVsyu9Ek3vILdtT42r0COHerllDZL9shIEEAs

### get a single tour
GET http://127.0.0.1:5000/api/v1/tours/67fb277d5a1348c725ab2a11
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDE5MjE5MiwiZXhwIjoxNzUxOTY4MTkyfQ.yGvs7t7W97zxoz6s7kPot7rwEc8mE1tG7k9ZS41OvYE


### post a tour
POST  http://127.0.0.1:5000/api/v1/tours
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTc0NDUxMjc1NywiZXhwIjoxNzUyMjg4NzU3fQ.9FO1ZJ9wDFm8sjZx5YfjaZ_Il6MWaY1DcZgOX5XqBMc
Content-Type: application/json

{
    "name": "test-tour-1",
    "duration": 9,
    "maxGroupSize": 8,
    "difficulty": "medium",
    "ratingsQuantity": 28,
    "price": 2997,
    "summary": "The most remote and stunningly beautiful places for seeing the night sky",
    "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "imageCover":"img.png"
}

### signup a new user 
POST  http://127.0.0.1:5000/api/v1/users/signup
Content-Type: application/json

{
  "name":"naol",
  "email":"naollll@gmail.com",
  "password":"Naol1234",
  "conformpassword":"Naol1234"
}

### login the user
POST  http://127.0.0.1:5000/api/v1/users/login
Content-Type: application/json

{
  "email":"ayls@example.com",
  "password":"test1234"
}


### login the user
GET   http://127.0.0.1:5000/api/v1/users
Content-Type: application/json

{
  "email":"admin@natours.io",
  "password":"test1234"
}

### forgote a password for the user 
post   http://127.0.0.1:5000/api/v1/users/forgotepassword
Content-Type: application/json

{
  "email":"user@gmail.com"
}

### reset the pasword with the sended token  
post   http://127.0.0.1:5000/api/v1/users/resetpassword/0e56282663900707305fb77dea006e8ee5bcd17c88df6d0eb91ef1f7b451fb04
Content-Type: application/json

{
  "password":"useruser",
  "conformpassword":"useruser"
}

### update the user pasword

post http://127.0.0.1:5000/api/v1/users/updatepassword/67f641e9db2dc10c7040be85
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDIwMTkyMCwiZXhwIjoxNzUxOTc3OTIwfQ.3yjHwjksz2oUAiSCMwJdZ5Wizrft3PCCPXeRSPMQOME
Content-Type: application/json

{
  "passwordCurrent":"useruser",
  "password":"useruser",
  "conformpassword":"useruser"

}

### delete a user 
post   http://127.0.0.1:5000/api/v1/users/deleteme
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjY0MWU5ZGIyZGMxMGM3MDQwYmU4NSIsImlhdCI6MTc0NDIwMTkyMCwiZXhwIjoxNzUxOTc3OTIwfQ.3yjHwjksz2oUAiSCMwJdZ5Wizrft3PCCPXeRSPMQOME
Content-Type: application/json

### get all users
GET http://127.0.0.1:5000/api/v1/users

### delete a  tour


### add a review to a tour 
post http://127.0.0.1:5000/api/v1/tours/67fb277d5a1348c725ab2a11/reviews
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZWM2MmY4ZmI4MTRiNTZmYTE4MyIsImlhdCI6MTc0NDUxMzA0NiwiZXhwIjoxNzUyMjg5MDQ2fQ.PdCUtR1rB1GwZYVzTNzPq2iQeDJgKqbkGLP0A28ev58
Content-Type: application/json

{
  "review":"fantastic tour",
  "rating":4
}

### update review 
patch http://127.0.0.1:5000/api/v1/review/67fbf9fd63f92f68a1ce174b
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZWM2MmY4ZmI4MTRiNTZmYTE4MyIsImlhdCI6MTc0NDUxMzA0NiwiZXhwIjoxNzUyMjg5MDQ2fQ.PdCUtR1rB1GwZYVzTNzPq2iQeDJgKqbkGLP0A28ev58
Content-Type: application/json

{
  "rating":3
}

### delte a user from admin

DELETE http://127.0.0.1:5000/api/v1/users/67fb1bd3c571c87c743d5a38



### me route
get http://127.0.0.1:5000/api/v1/users/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTc0NDUwODgzMSwiZXhwIjoxNzUyMjg0ODMxfQ.bcqDxq8vAipzOcqumsrnQGw1QpnsxPad3lAlgXNJT_s
Content-Type: application/json


### finding the nearest tour 
/distance/:latlng/unit/:unit
get http://127.0.0.1:5000/api/v1/tours/tours-withn/400/center/-117.97,34/unit/km
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTc0NDUwODgzMSwiZXhwIjoxNzUyMjg0ODMxfQ.bcqDxq8vAipzOcqumsrnQGw1QpnsxPad3lAlgXNJT_s
Content-Type: application/json


### calculate the distance from my point 

get http://127.0.0.1:5000/api/v1/tours/distance/-117.97,34/unit/mi
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTc0NDUwODgzMSwiZXhwIjoxNzUyMjg0ODMxfQ.bcqDxq8vAipzOcqumsrnQGw1QpnsxPad3lAlgXNJT_s
Content-Type: application/json